# Generated by Django 5.1.6 on 2025-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
