# Generated by Django 5.1.6 on 2025-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateapp', '0002_visitor_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
